### ISSUE TITLE
How to use 'And', 'Or', etc. in config files ?

### ISSUE THREAD

**Issue by k0pfweh** [charliefoxtwo/ViLA#12]
I've done a quick and dirty approach on writing an Elite: Dangerous Plugin.
Im trying to set a led to a different color if two values are true.

Example:

ELITE_LDG_DWN (Landing Gear Down): led is blue   (working)
ELITE_LDG_DWN and (ELITE_DOCKED or ELITE_LANDED) led is green

I can't figure out the correct syntax for the second one.

**Comment by charliefoxtwo** [comment]
Awesome! Sorry it's taken me so long to respond. 

One thing to keep in mind is that the first rule will always be true. ViLA will run any rules which are true, when means that even if the second is correct it could then be overwritten by the first.

Your first rule should probably be ELITE_LDG_DWN and NOT(ELITE_DOCKED or ELITE_LANDED)

Here's a sample AND configuration I had written up in discord. These can be nested as deep as you like. 
```json
{
    "color": "ff0000",
    "trigger": {
        "value": [
            {
                "id": "c",
                "value": 1,
                "comparator": "EqualTo"
            },
            {
                "id": "d",
                "value": 1,
                "comparator": "EqualTo"
            }
        ],
        "comparator": "And"
    }
},
```

**Comment by k0pfweh** [comment]
Thanks 👍 I'll give it a try later this week :)
